### ISSUE TITLE
Качество

### ISSUE THREAD

**Issue by AMSHL** [eschava/soap4me-proxy#1]
Серия всегда подтягивается с SD качеством, вне зависимости от того, что ты выбрал в настройках. Про поддержку только одного типа в качества для серии в Коди - понятно. Но похоже сейчас выбирается вариант не с самым подходящим вариантом по качеству, а с минимальным. 
Upd - проблема оказалась в том, что не обновлялся файл настроек аддона.

**Comment by eschava** [comment]
В чем была проблема с файлом настроек?
